image: registry.gitlab.com/iniparser/docker-cmake:latest

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    LD_LIBRARY_PATH: ${CI_BUILDS_DIR}/iniparser/iniparser/install/lib/


stages:
    - build
    - doc
    - test
    # due to the long provisioning time, windows gets its own stages
    - win-build
    - win-exe

build:
    stage: build
    script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_INSTALL_PREFIX=../install -DBUILD_TESTING=ON -DBUILD_EXAMPLES=ON ..
        - make install
        - tree -a .
    artifacts:
        paths:
            - install/
            - build/

pages:
    stage: doc
    dependencies:
        - build
    script:
        - mv build/html/ public/
    artifacts:
        paths:
            - public
    rules:
        - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

test:
    stage: test
    script:
        - pwd
        - ls -l
        - cd build/
        - ctest --verbose
    dependencies:
        - build

memcheck:
    stage: test
    script:
        - pwd
        - ls -l
        - cd build/
        - valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --error-exitcode=255 ctest --verbose
    dependencies:
        - build

iniexample-memcheck:
    stage: test
    script:
        - pwd
        - tree
        - cd install/share/doc/iniparser/examples/
        - valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --error-exitcode=255 ./iniexample
    dependencies:
        - build

iniwrite-memcheck:
    stage: test
    script:
        - pwd
        - tree
        - cd install/share/doc/iniparser/examples/
        - valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --error-exitcode=255 ./iniwrite
    dependencies:
        - build

parse-memcheck:
    stage: test
    script:
        - pwd
        - tree
        - cd install/share/doc/iniparser/examples/
        - valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --error-exitcode=255 ./parse
    dependencies:
        - build

.shared_windows_runners:
    tags:
        - saas-windows-medium-amd64

win-build:
    extends:
        - .shared_windows_runners
    stage: win-build
    script:
        - Get-ChildItem C:\tools\Ruby31
        - Get-ChildItem C:\tools\Ruby31\lib
        - Get-ChildItem "$env:VSAPPIDDIR..\Tools\vsdevcmd\ext\"
        - cd C:\tools\Ruby31\lib
        - cmd /c call "%VSAPPIDDIR%..\Tools\vsdevcmd\ext\vcvars.bat"
        - echo LIBRARY LIBX64-UCRT-RUBY310 > libx64-ucrt-ruby310.def
        - echo EXPORTS >> libx64-ucrt-ruby310.def
        - cmd /c for /f "skip=19 tokens=4" %A in $(cmd /c dumpbin /exports libx64-ucrt-ruby310.dll.a) do echo %A >> libx64-ucrt-ruby310.def
        - cmd /c lib /def:libx64-ucrt-ruby310.def /out:libx64-ucrt-ruby310.lib /machine:x86
        - cd C:/GitLab-Runner/builds/iniparser/iniparser/
        - mkdir build
        - cd build
        - cmake -DRuby_POSSIBLE_LIB_DIR="C:\tools\Ruby31\lib\" -DCMAKE_INSTALL_PREFIX=..\install -DBUILD_DOCS=OFF -DBUILD_TESTING=ON -DBUILD_EXAMPLES=ON ..
        - cmake --build .
    artifacts:
        paths:
            - install/
            - build/
    dependencies: []

win-test:
    extends:
        - .shared_windows_runners
    stage: win-exe
    script:
        - cd build/
        - ctest --verbose
    dependencies:
        - win-build
    artifacts:
        paths:
            - build/test/
    dependencies: []

win-examples:
    stage: win-exe
    script:
        - cd install/share/doc/iniparser/examples/
        - ./iniexample
        - ./iniwrite
        - ./parse
    dependencies:
        - win-build
